---
title: "git_01"
author: "Liberty Montez"
date: "Summer semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A Mother's breast:  
Safe refuge from her childish fears,  
From childish troubles, childish tears,  
Mists that enshroud her dawning years!  
see how in sleep she seems to sing  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
He is that fallen lance that lies as hurled,  
That lies unlifted now, come dew, come rust,  
But still lies pointed as it plowed the dust.  
If we who sight along it round the world,  
See nothing worthy to have been its mark,  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
        
## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
Ten true friends you have,  
Who, five in a row,  
Upon each side of you  
Go where you go.  
Suppose you are sleepy,  
They help you to bed;  
Suppose you are hungry,  
They see that you are fed.  
They wake up your dolly  
And put on your clothes,  
And trundle her carriage  
Wherever she goes.  
And these ten tiny fellows,  
They serve you with ease;  
And they ask nothing from you,  
But work hard to please.  
Now, with ten willing servants  
So trusty and true,  
Pray who would be lazy  
Or idle—would you?  
  